project_id = "oymskyusykbcdrdrcpzd"

[functions.admin-reset-password]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.login]
verify_jwt = false

[functions.logout]
verify_jwt = false

[functions.update-permissions]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.register-empresa]
verify_jwt = false

[functions.process-checkout]
verify_jwt = false

[functions.create-empresa]
verify_jwt = false

[functions.update-user-password]
verify_jwt = false

[functions.update-password]
verify_jwt = false

[functions.delete-empresa]
verify_jwt = false

[functions.process-docx]
verify_jwt = false
